name: AutoUpdate

on: 
  schedule:
    - cron: "5 12 * * 6"
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Fetch and update cases
      run: python update.py
    - name: Commit changes 
      uses: EndBug/add-and-commit@v2.1.0 
      # Commit only if this is not a PR
      if: github.ref == 'master' 
      with: 
        author_name: GitHub Action
        author_email: action@github.com
        message: "Add new cases!"
        path: "."
        pattern: "*.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
